"""
app/models/database.py — SQLAlchemy ORM table definitions
===========================================================
These classes are the single source of truth for the database schema.
Each class maps to one Postgres table. Each class attribute maps to one column.

Two tables:
  Conversation — one row per chat session
  Message      — one row per message (user or assistant) in a conversation

Why SQLAlchemy ORM vs raw SQL?
  Raw SQL works, but it spreads query strings across the codebase with no type
  safety — a typo in a column name fails at runtime, not at type-check time.
  SQLAlchemy lets you reference columns as Python attributes:
    session.execute(select(Message).where(Message.conversation_id == cid))
  Your editor autocompletes them. mypy catches typos. Refactoring a column
  name is a single search-and-replace, not a grep through SQL strings.

Why UUIDs as primary keys vs auto-increment integers?
  Integer IDs (1, 2, 3...) are sequential and predictable. A user who knows
  their conversation is id=5 can guess id=4 exists and try to access it —
  an enumeration attack. UUIDs (e.g. "b8f3a21c-4d2e-4f1a-9c3b-...") are
  128-bit random values: statistically impossible to guess. They also work
  safely in distributed systems where multiple nodes generate IDs in parallel.

Why DeclarativeBase?
  DeclarativeBase is the modern SQLAlchemy 2.0 way to define the ORM base class.
  All ORM models inherit from it. The `metadata` object attached to it is what
  Alembic inspects to discover tables and generate migration scripts.
"""

import enum
import uuid
from datetime import datetime

from sqlalchemy import DateTime, Enum, ForeignKey, Integer, String, Text, func
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship


class Base(DeclarativeBase):
    """
    Base class for all ORM models.

    Every table class inherits from this. SQLAlchemy uses this to:
      1. Register the class in the metadata registry (so Alembic can find it)
      2. Provide the `__tablename__` convention
      3. Supply helper methods like `.dict()` added below

    We define it here rather than in a separate file so all models can import
    from one place: `from app.models.database import Base, Conversation, Message`
    """
    pass


class MessageRole(str, enum.Enum):
    """
    Postgres ENUM type for the role of a message in a conversation.

    Why an enum instead of a plain string column?
      - Database-level constraint: Postgres rejects any value not in the enum.
        A bug that writes role="bot" instead of role="assistant" is caught at
        the DB layer, not silently stored as bad data.
      - Inheriting from str means the values can be used directly as strings
        in Python: MessageRole.USER == "user" → True. No need to call .value.
    """
    USER = "user"
    ASSISTANT = "assistant"


class Conversation(Base):
    """
    Represents one chat session between a user and the assistant.

    A conversation is a container for messages. Its only job is to group
    messages together and provide a stable ID the client can reference across
    multiple requests ("continue this conversation").

    Schema:
      id         — UUID primary key, random, generated by Postgres
      created_at — when the conversation started (set once, never updated)
      updated_at — when the last message was added (auto-updated by Postgres)
    """
    __tablename__ = "conversations"

    id: Mapped[uuid.UUID] = mapped_column(
        # UUID is a Postgres-native type — stored as 16 bytes, not a 36-char string.
        # as_uuid=True means SQLAlchemy returns Python uuid.UUID objects, not raw strings.
        UUID(as_uuid=True),
        primary_key=True,
        # server_default: the DEFAULT is set in Postgres, not in Python.
        # This means the ID is generated even if you INSERT via raw SQL or a migration.
        default=uuid.uuid4,
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        # server_default=func.now() → Postgres sets this to NOW() on INSERT.
        # Using the server clock (not Python's datetime.now()) is important for
        # distributed systems: if multiple app instances have slightly different
        # system clocks, server_default keeps timestamps consistent.
        server_default=func.now(),
        nullable=False,
    )

    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        # onupdate=func.now() → Postgres updates this automatically whenever
        # any column in this row is modified. You get a free "last modified"
        # timestamp with no application-level code needed.
        onupdate=func.now(),
        nullable=False,
    )

    # Relationship: one Conversation has many Messages.
    # back_populates="conversation" links this to Message.conversation.
    # lazy="select" means messages are loaded in a separate query when accessed
    # (not eagerly joined). For our use case (loading history explicitly), this
    # is the right default.
    messages: Mapped[list["Message"]] = relationship(
        "Message",
        back_populates="conversation",
        order_by="Message.created_at",  # always return messages in chronological order
    )


class Message(Base):
    """
    Represents one message in a conversation — either from the user or the assistant.

    Schema:
      id              — UUID primary key
      conversation_id — foreign key → conversations.id (CASCADE DELETE:
                        deleting a conversation deletes all its messages)
      role            — "user" or "assistant" (Postgres ENUM, enforced at DB level)
      content         — the full text of the message (TEXT = unlimited length)
      tokens_used     — token count returned by the Anthropic API for this message.
                        Nullable: user messages don't consume tokens (only assistant
                        responses do). Used for cost tracking and Langfuse tracing.
      created_at      — when the message was created
    """
    __tablename__ = "messages"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
    )

    conversation_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        # ForeignKey links this column to conversations.id.
        # ondelete="CASCADE" means: when a Conversation row is deleted,
        # Postgres automatically deletes all Message rows for that conversation.
        # Without CASCADE, deleting a conversation would fail with a foreign key
        # constraint violation because child Message rows still reference it.
        ForeignKey("conversations.id", ondelete="CASCADE"),
        nullable=False,
        index=True,  # index because we frequently query messages by conversation_id
    )

    role: Mapped[MessageRole] = mapped_column(
        # SQLAlchemy maps Python's MessageRole enum to a Postgres ENUM type.
        # The enum is created in the database during migration.
        Enum(MessageRole, name="message_role"),
        nullable=False,
    )

    content: Mapped[str] = mapped_column(
        Text,  # TEXT in Postgres: unlimited length, stored efficiently
        nullable=False,
    )

    tokens_used: Mapped[int | None] = mapped_column(
        Integer,
        # nullable=True (default): user messages don't have a token count.
        # Only assistant responses have tokens_used set (from Anthropic's response).
        nullable=True,
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )

    # Relationship back to the parent Conversation.
    # Accessing message.conversation loads the full Conversation object.
    conversation: Mapped["Conversation"] = relationship(
        "Conversation",
        back_populates="messages",
    )
